spring:
  profiles:
    active: dev
#spring:
#  autoconfigure:
#    #自动化配置 例外处理
#    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
#  datasource:
#    dynamic:
#      primary: master # 配置默认数据库
#      datasource:
##        strict: false
#        master: # 数据源1配置
#          url: jdbc:mysql://localhost:3306/ttms?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#          type: com.alibaba.druid.pool.DruidDataSource
#          username: root
#          password: 13468724917qkm,
#          driver-class-name: com.mysql.cj.jdbc.Driver
#        slave: # 数据源2配置
#          url: jdbc:mysql://localhost:3306/Text?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#          type: com.alibaba.druid.pool.DruidDataSource
#          username: root
#          password: 13468724917qkm,
#          driver-class-name: com.mysql.cj.jdbc.Driver
#      durid:
#        initial-size: 1
#        max-active: 20
#        min-idle: 1
#        max-wait: 60000
---
server:
  port: 8081
spring:
  multipart.enabled: true
  multipart.file-size-threshold: 0
  servlet:
    # 一个文件的限制大小
    multipart.max-file-size: 30MB
    # 单次请求的文件限制大小
    multipart.max-request-size: 30MB
  profiles: dev
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/ttms?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 13468724917qkm,
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  redis:
    host: 127.0.0.1
    port: 6379
#    databases: [ 0,1,2,3,4] # 要使用的库，会根据此处填写的库生成redisTemplate
#    timeout: 60s
#    lettuce: # lettuce基于netty，线程安全，支持并发
  messages:
    basename: i18n.login
  thymeleaf:
    cache: false

p6spy:
  config:
    appender: com.p6spy.engine.spy.appender.Slf4JLogger
    logMessageFormat: com.p6spy.engine.spy.appender.CustomLineFormat
    customLogMessageFormat: executionTime:%(executionTime)|执行sql:%(sqlSingleLine)
    executionThreshold: 20
---
spring:
  profiles: prod
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/ttms?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 13468724917qkm,
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    redis:
      host: 127.0.0.1
      port: 6380
    #    databases: [ 0,1,2,3,4] # 要使用的库，会根据此处填写的库生成redisTemplate
    #    timeout: 60s
    #    lettuce: # lettuce基于netty，线程安全，支持并发
    messages:
      basename: i18n.login
    thymeleaf:
      cache: false

  p6spy:
    config:
      appender: com.p6spy.engine.spy.appender.Slf4JLogger
      logMessageFormat: com.p6spy.engine.spy.appender.CustomLineFormat
      customLogMessageFormat: executionTime:%(executionTime)|执行sql:%(sqlSingleLine)
      executionThreshold: 20
server:
  port: 8081