spring:
  autoconfigure:
    #自动化配置 例外处理
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      primary: master # 配置默认数据库
      datasource:
#        strict: false
        master: # 数据源1配置
          url: jdbc:mysql://localhost:3306/ttms?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
          type: com.alibaba.druid.pool.DruidDataSource
          username: root
          password: 13468724917qkm,
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave: # 数据源2配置
          url: jdbc:mysql://localhost:3306/Text?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
          type: com.alibaba.druid.pool.DruidDataSource
          username: root
          password: 13468724917qkm,
          driver-class-name: com.mysql.cj.jdbc.Driver
      durid:
        initial-size: 1
        max-active: 20
        min-idle: 1
        max-wait: 60000
  redis:
    host: 127.0.0.1
    port: 6380
  messages:
    basename: i18n.login
  thymeleaf:
    cache: false
#p6spy:
#  config:
#    appender: com.p6spy.engine.spy.appender.Slf4JLogger
#    logMessageFormat: com.p6spy.engine.spy.appender.CustomLineFormat
#    customLogMessageFormat: executionTime:%(executionTime)|执行sql:%(sqlSingleLine)
#    executionThreshold: 20
